apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafing
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.devops-expert.foundation
    http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              number: 3000
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
