apiVersion: v1
data:
  mapUsers: |
    - userarn: arn:aws:iam::598792377165:user/devuser
      username: developer
      groups:
      - developer
    - userarn: arn:aws:iam::598792377165:user/eksadmin
      username: eksadmin
      groups:
      - eksadmin
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::598792377165:role/eks-node-group-role
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-12-31T14:30:00Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "928"
  uid: 15908da9-ad35-4895-8ab5-6e816f9e58a7