apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proming
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: prom.devops-expert.foundation
    http:
      paths:
      - backend:
          service:
            name: prometheus-kube-prometheus-prometheus
            port:
              number: 9090
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
