apiVersion: v1
kind: ConfigMap
metadata:
  name: test-auth
  namespace: dev
data:
  mapUsers: |
    - userarn: arn:aws:iam::598792377165:user/devuser
      username: developer
      groups:
      - developer