# Development configuration with Kustomization
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
bases:
- ../../../base/ingress


patches:
- replicas.yaml
- addrole.yaml

configMapGenerator:
  - name: test-auth
    behavior: merge
    envs:
    - env-vars