apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  strategy: {}
  template:
    metadata:
      labels:
        app: app1
    spec: 
      containers:
      - name: nginxmyimage