name: 'Terraform'

on:
  push:
    branches: ["development", "staging", "production"]
  pull_request:
    branches: ["staging", "production"]

env:
  CLUSTER_NAME: EKS-GitOps-Cluster
  REGION: ap-south-1
  CURRENT_DIR: ~/work/eks-argo-gitops/eks-argo-gitops/terraform/environment/development/
  SCRIPTS_DIR: ~/work/eks-argo-gitops/eks-argo-gitops/terraform/environment/scripts/
  TFVARS_FILE: ~/work/eks-argo-gitops/eks-argo-gitops/terraform/environment/development/terraform.tfvars
      

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash
        working-directory: terraform/environment/${GITHUB_REF##*/}/

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials with OIDC and Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.OIDC_ARN }}
        aws-region: ap-south-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.3

    - name: Terraform Init
      run: |
        terraform init

    - name: Terraform Format
      run: |
        terraform fmt

    - name: Terraform validate
      run: terraform validate
      
    # Setup TFLint
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.54.0

    # Initialize TFLint
    - name: TFLint init
      run: tflint --init

    # Run TFLint
    - name: TFLint
      run: tflint --recursive

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false -var-file="${TFVARS_FILE}" -out=tfplan


    # - name: AWS EKS Cluster status check and kubectl configure
    #   id: eks_status
    #   run: |
    #     aws --version
    #     aws s3 ls
    #     echo '#Install kubectl'
    #     curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    #     sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    #     kubectl version --client
    #     cd ../scripts/
    #     chmod +x check_eks_status.sh
    #     ./check_eks_status.sh

  #   - name: Terraform Plan
  #     run: |
  #       terraform plan -input=false

  #   - name: Terraform Apply for Network and EKS modules
  #     if: github.ref == 'refs/heads/development' && github.event_name == 'push'
  #     run: |
  #       cd terraform/environment/${GITHUB_REF##*/}/
  #       terraform apply -target=module.main_network -target=module.eks_gitops_cluster --auto-approve -input=false

  #   - name: Terraform Apply HELM Module
  #     if: github.ref == 'refs/heads/development' && github.event_name == 'push'
  #     run: |
  #       cd terraform/environment/scripts/
  #       ./check_eks_status.sh
  #       cd ../${GITHUB_REF##*/}/
  #       echo "Apply helm module"
  #       terraform apply -target=module.helm_repos --auto-approve -input=false

  # kubernetes:
  #   needs: [terraform]
  #   name: 'Kubernetes'
  #   runs-on: ubuntu-latest
  #   environment: development

  #   defaults:
  #     run:
  #       shell: bash

  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   - name: Configure AWS credentials with OIDC and Role
  #     uses: aws-actions/configure-aws-credentials@v4
  #     with:
  #       role-to-assume: ${{ secrets.OIDC_ARN }}
  #       aws-region: ap-south-1

  #   - name: Apply Ingress with Kustomize
  #     run: |
  #       cd terraform/environment/scripts/
  #       chmod +x check_eks_status.sh
  #       ./check_eks_status.sh
  #       cd ../../../kubernetes/overlays/development/ingress
  #       pwd
  #       echo 'Apply Ingress with Kustomize'
  #       kubectl kustomize .
  #       kubectl apply -k .
  #       kubectl get po -n dev

  #   - name: Test Sample application
  #     run: |
  #       cd terraform/environment/scripts/
  #       chmod +x check_eks_status.sh
  #       ./check_eks_status.sh
  #       cd ../../../kubernetes/overlays/development/
  #       pwd
  #       kubectl get ns
  #       kubectl create ns dev --dry-run=client -o yaml | kubectl apply -f -
  #       echo 'Test Kustomize'
  #       kubectl kustomize .
  #       kubectl apply -k .
  #       kubectl get all -n dev
